apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: vv-dev
    devEnvApprovers:
    - svcngcc
    environmentGitOwner: svcngcc
    gitKind: gitlab
    gitName: gitlab
    gitServer: https://gitlab-master.nvidia.com
    provider: kubernetes
    registry: sc-hw-artf.nvidia.com
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: "jenkins-x.nonprod-nvkong.com"
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
